#!/usr/bin/env python

import sys
import csv
import shelve
import math
import random

from project.document import Document
from project.api import *


def main(model_file_path,test_file_path,prediction_file_path):
    with open(prediction_file_path,"w") as prediction_file:
        test_list = Document(test_file_path, "test",use_bigrams=False).model
        shelf = shelve.open(model_file_path)
        labels = [bayes_bagging(shelf["models"],instance) for instance in test_list]
        for label in labels:
            prediction_file.write(label+"\n")
        shelf.close()




if __name__ == '__main__':
    model_file_path = sys.argv[1]
    test_file_path = sys.argv[2]
    prediction_file_path = sys.argv[3]
    main(model_file_path, test_file_path, prediction_file_path)
        
