#!/usr/bin/env python

import sys
from project.api import naive_bayes

def train(input_path,output_path):
    naive_bayes(input_path,output_path)


if __name__ == '__main__':
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    print "INPUT:", input_path
    print "OUTPUT: ", output_path
    train(input_path,output_path)





